---
#####################################
### Create static OUs
#####################################

- name: Create static OUs
  microsoft.ad.ou:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    state: present
    protect_from_deletion: true
  with_items: "{{ dc_ous_static }}"

#####################################
### Create dynamic OUs
#####################################

- name: dingledongel
  ansible.builtin.debug:
    msg: "{{ item.0.name }} - {{ item.0.path | replace('##', item.1 ) }} - {{ item.1 }} "
  with_nested:
    - "{{ dc_ous_dynamic }}"
    - "{{ range(1, dc_domain_count + 1, 1) | list }}"

- name: Create dynamic OUs  
  microsoft.ad.ou:
    name: "{{ item.0.name }}"
    path: "{{ item.0.path | replace('##', item.1 ) }}"
    state: present
    protect_from_deletion: true
  with_items: 
  - "{{ dc_ous_dynamic }}"
  - "{{ range(1, dc_domain_count + 1, 1) | list }}"