---
#####################################
### Create OUs
#####################################

- name: Write output
  debug:
    msg: "{{ item.name }} and {{ item.path }}"
  with_items: "{{ ous }}"

- name: Ensure OU is present & protected    
  community.windows.win_domain_ou:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    state: present
    protected: true
  with_items: "{{ ous }}"