---
#####################################
### Create OUs
#####################################

#- name: Ensure OU is present & protected
#  community.windows.win_domain_ou:
#    name: Objects
#    path: "DC=dt,DC=democloud"
#    state: present
#    protected: true

- name: Iterating over nested lists
  debug:
    msg: "{{ item[0] }} and {{ item[1] }} "
  loop: "{{ server1.custom_mountpoints | product(snmp_mountpoints_extends) | list }}"