---
#####################################
### Create OUs
#####################################

- name: Ensure OU is present & protected
  debug:
    msg: "{{ item.name }} and {{ item.path }}"
  community.windows.win_domain_ou:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    state: present
    protected: true
  with_items: "{{ ous }}"