---
#####################################
### Create OUs
#####################################

- name: Ensure OU is present & protected    
  microsoft.ad.ou:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    state: present
    protect_from_deletion: true
  with_items: "{{ dc_ou }}"