---
#####################################
### Create OUs
#####################################

#- name: Ensure OU is present & protected
#  community.windows.win_domain_ou:
#    name: Objects
#    path: "DC=dt,DC=democloud"
#    state: present
#    protected: true

- name: set_fact
  args:
    userslist:
      name: '{{ item.0.name }}'
      path:  '{{ item.0.path }}'
  with_subelements: 
    - ous