---
#####################################
### Create static OUs
#####################################

- name: Create static OUs
  microsoft.ad.ou:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    state: present
    protect_from_deletion: true
  with_items: "{{ dc_ous_static }}"

#####################################
### Create dynamic OUs
#####################################

- name: Create dynamic OUs 
  microsoft.ad.ou:
    name: "{{ item.0.name | replace('ee', 'banana') }}"
    path: "OU=Objects,DC=dt,DC=training"
    state: present
    protect_from_deletion: true
  with_nested:
  - "{{ dc_ous_dynamic }}"
  - "{{ range(1, dc_domain_count + 1, 1) | list }}"

